name: Render

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Render list
        run: make render
        
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          branch: ${{ github.head_ref }}
          commit_message: Commit list
          commit_user_name: Jie_0Y
          commit_user_email: Jie_0Y@163.com
          commit_author: Jie_0Y <Jie_0T@163.com>
